# SubServer Plugin Configuration
# This is The Main Config for this Plugin
#
# These are the Plugin Settings
Settings:
    Server-Creation:
        git-dir: 'C:\Program Files\Git'
        log: true
    config-version: 1.8.9a+
    GUI:
        Enabled: true
        Trigger-Item: '129'
    Server-IP: '127.0.0.1'
    Lobby-Port: 25565
    SQL:
        hostname: '127.0.0.1'
        port: 3306
        username: 'root'
        password: ''
        database: 'minecraft'
#
# This is the settings for the proxy
Proxy:
    enabled: false
    run-on-launch: true
    log: true
    dir: './Folder'
    exec: 'java -Djline.terminal=jline.UnsupportedTerminal -jar SubServers.Bungee.jar'
    auto-restart: false
#
# This Is the List of your Servers
# And their configurations
Servers:
    'My-Cool-Server':
        enabled: false
        port: 25565
        run-on-launch: false
        use-shared-chat: true
        log: true
        dir: './Folder'
        exec: 'java -Djline.terminal=jline.UnsupportedTerminal -jar Spigot.jar'
        auto-restart: false
#
# End of Config