# SubServer Plugin Configuration
# This is The Main Config for this Plugin
#
# Where is git Located? Mac/Linux users can ignore this option
Settings:
    Server-Creation:
        git-dir: 'C:\Program Files\Git'
        log: true
    config-version: 1.8.8k+
    GUI:
        Enabled: true
        Trigger-Item: '129'
    Server-IP: '127.0.0.1'
    Lobby-Port: 25565
#
# This is the settings for the proxy
Proxy:
    enabled: false
    run-on-launch: true
    dir: './Folder'
    exec: 'java -Djline.terminal=jline.UnsupportedTerminal -jar SubServers.Bungee.jar'
    log: true
#
# This Is the List of your Servers
# And their configurations
Servers:
    'My-Cool-Server':
        enabled: false
        port: 25565
        run-on-launch: false
        use-shared-chat: true
        log: true
        dir: './Folder'
        exec: 'java -Djline.terminal=jline.UnsupportedTerminal -jar Spigot.jar'
        stop-after: 0
#
# End of Config