player_limit: -1
ip_forward: true
permissions:
  default:
  - bungeecord.command.server
  - bungeecord.command.list
  admin:
  - bungeecord.command.find
  - bungeecord.command.alert
  - bungeecord.command.send
  - bungeecord.command.end
  - bungeecord.command.ip
  - bungeecord.command.reload
timeout: 30000
online_mode: true
servers:
  '~Lobby':
    motd: '&aJust another SubServer'
    address: localhost:25566
    restricted: false
    use-shared-chat: false
listeners:
- query_port: 25577
  motd: '&1Another SubServer Proxy'
  tab_list: GLOBAL_PING
  query_enabled: false
  forced_hosts:
    pvp.md-5.net: pvp
  ping_passthrough: true
  default_server: '~Lobby'
  bind_local_address: true
  fallback_server: '~Lobby'
  host: 0.0.0.0:25565
  max_players: 1
  tab_size: 60
  force_default_server: true
disabled_commands: []
network_compression_threshold: 256
groups:
  ME1312:
  - admin
connection_throttle: 4000
stats: 9b8926b9-a8a1-453e-88d9-9c66384518f8
